extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - "@koishijs"
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/no-namespace": off
  "@typescript-eslint/require-await": off
