git:
  commitMessage: "chore: release v${version}"
github:
  release: true
npm:
  publish: false
hooks:
  before:git:release: 'node --input-type module -e "await (await import(''fs/promises'')).rm(''../../package-lock.json'', {force: true})"; yarn install'
plugins:
  "@release-it/conventional-changelog":
    preset: conventionalcommits
    infile: CHANGELOG.md
