git:
  commitMessage: "chore: release v${version}"
github:
  release: true
npm:
  publish: false
hooks:
  after:version:bump: yarn install
plugins:
  "@release-it/conventional-changelog":
    preset: conventionalcommits
    infile: CHANGELOG.md
