name: Publish To NPM
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    name: "Build and publish to NPM"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/

      - name: Install yarn3
        run: |
          yarn set version stable
      - name: Install deps and build
        run: |
          yarn install --no-immutable
          yarn build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn config set npmAuthToken $NODE_AUTH_TOKEN
          yarn npm publish
